// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Passion.Models;

#nullable disable

namespace Passion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250903154753_Passion")]
    partial class Passion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Passion.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Passion.Models.MasterAboutUs", b =>
                {
                    b.Property<int>("MasterAboutUsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterAboutUsId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterAboutUsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterAboutUsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterAboutUsId");

                    b.ToTable("MasterAboutUs");
                });

            modelBuilder.Entity("Passion.Models.MasterChooseCategory", b =>
                {
                    b.Property<int>("MasterChooseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterChooseCategoryId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterChooseCategoryBreef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterChooseCategoryIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterChooseCategoryTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterChooseCategoryId");

                    b.ToTable("MasterChooseCategory");
                });

            modelBuilder.Entity("Passion.Models.MasterChooseItemMenu", b =>
                {
                    b.Property<int>("MasterChooseItemMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterChooseItemMenuId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("MasterChooseCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("MasterChooseItemMenuBreef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterChooseItemMenuDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterChooseItemMenuImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterChooseItemMenuList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterChooseItemMenuTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterChooseItemMenuId");

                    b.HasIndex("MasterChooseCategoryId");

                    b.ToTable("MasterChooseItemMenu");
                });

            modelBuilder.Entity("Passion.Models.MasterContactUs", b =>
                {
                    b.Property<int>("MasterContactUsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterContactUsId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterContactUsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterContactUsEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterContactUsPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterContactUsId");

                    b.ToTable("MasterContactUs");
                });

            modelBuilder.Entity("Passion.Models.MasterContactUsInformation", b =>
                {
                    b.Property<int>("MasterContactUsInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterContactUsInformationId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterContactUsInformationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterContactUsInformationIcon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterContactUsInformationId");

                    b.ToTable("MasterContactUsInformation");
                });

            modelBuilder.Entity("Passion.Models.MasterFeature", b =>
                {
                    b.Property<int>("MasterFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterFeatureId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterFeatureBreef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFeatureDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFeatureImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFeatureTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFeatureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterFeatureId");

                    b.ToTable("MasterFeature");
                });

            modelBuilder.Entity("Passion.Models.MasterFeatures", b =>
                {
                    b.Property<int>("MasterFeaturesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterFeaturesId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterFeaturesBreef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFeaturesIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MasterFeaturesNumber")
                        .HasColumnType("int");

                    b.Property<string>("MasterFeaturesTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterFeaturesId");

                    b.ToTable("MasterFeatures");
                });

            modelBuilder.Entity("Passion.Models.MasterFocus", b =>
                {
                    b.Property<int>("MasterFocusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterFocusId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterFocusBreef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusFullSecurityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusFullSecurityIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusMoneyBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusQuickSetupDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusQuickSetupIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusRatingIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterFocusUsersIcon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterFocusId");

                    b.ToTable("MasterFocus");
                });

            modelBuilder.Entity("Passion.Models.MasterHowWeWork", b =>
                {
                    b.Property<int>("MasterHowWeWorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterHowWeWorkId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterHowWeWorkBreef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterHowWeWorkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterHowWeWorkIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterHowWeWorkTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterHowWeWorkId");

                    b.ToTable("MasterHowWeWork");
                });

            modelBuilder.Entity("Passion.Models.MasterMenu", b =>
                {
                    b.Property<int>("MasterMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterMenuId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterMenuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterMenuUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterMenuId");

                    b.ToTable("MasterMenu");
                });

            modelBuilder.Entity("Passion.Models.MasterOurServices", b =>
                {
                    b.Property<int>("MasterOurServicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterOurServicesId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterOurServicesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterOurServicesUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterOurServicesId");

                    b.ToTable("MasterOurServices");
                });

            modelBuilder.Entity("Passion.Models.MasterPartner", b =>
                {
                    b.Property<int>("MasterPartnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterPartnerId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterPartnerLogoImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPartnerWebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterPartnerId");

                    b.ToTable("MasterPartner");
                });

            modelBuilder.Entity("Passion.Models.MasterPortfolioCategoryMenu", b =>
                {
                    b.Property<int>("MasterPortfolioCategoryMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterPortfolioCategoryMenuId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterPortfolioCategoryMenuName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterPortfolioCategoryMenuId");

                    b.ToTable("MasterPortfolioCategoryMenu");
                });

            modelBuilder.Entity("Passion.Models.MasterPortfolioItemMenu", b =>
                {
                    b.Property<int>("MasterPortfolioItemMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterPortfolioItemMenuId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("MasterPortfolioCategoryMenuId")
                        .HasColumnType("int");

                    b.Property<string>("MasterPortfolioItemMenuBreef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsActiveUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsAppStoreRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsClientSatisfaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsDescription1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsFeatures1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsFeatures2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsFeatures3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsMonthsDevelopment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsTechnologiesUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsTheChallenge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsTheSolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuDetailsUrlCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPortfolioItemMenuTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterPortfolioItemMenuId");

                    b.HasIndex("MasterPortfolioCategoryMenuId");

                    b.ToTable("MasterPortfolioItemMenu");
                });

            modelBuilder.Entity("Passion.Models.MasterPricing", b =>
                {
                    b.Property<int>("MasterPricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterPricingId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterPricingBreef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPricingDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPricingIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPricingTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterPricingUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterPricingId");

                    b.ToTable("MasterPricing");
                });

            modelBuilder.Entity("Passion.Models.MasterQuestions", b =>
                {
                    b.Property<int>("MasterQuestionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterQuestionsId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterQuestionsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterQuestionsIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterQuestionsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterQuestionsId");

                    b.ToTable("MasterQuestions");
                });

            modelBuilder.Entity("Passion.Models.MasterService", b =>
                {
                    b.Property<int>("MasterServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterServiceId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterServiceClientSatisfaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServiceProjectsCompleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServiceSupportAvailable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServiceYearsExperience")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterServiceId");

                    b.ToTable("MasterService");
                });

            modelBuilder.Entity("Passion.Models.MasterServices", b =>
                {
                    b.Property<int>("MasterServicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterServicesId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterServicesDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsBreef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsDescriptionOurProcess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsDescriptionWhatYouWillGet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsList1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsList2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsNeedHelpDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsNeedHelpEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsNeedHelpIconEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsNeedHelpIconPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsNeedHelpPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsNeedHelpUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesDetailsTitleImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterServicesUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterServicesId");

                    b.ToTable("MasterServices");
                });

            modelBuilder.Entity("Passion.Models.MasterSocialMedium", b =>
                {
                    b.Property<int>("MasterSocialMediumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterSocialMediumId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterSocialMediumIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterSocialMediumUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterSocialMediumId");

                    b.ToTable("MasterSocialMedium");
                });

            modelBuilder.Entity("Passion.Models.MasterTeam", b =>
                {
                    b.Property<int>("MasterTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterTeamId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterTeamBreef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterTeamDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterTeamIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterTeamIconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterTeamImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterTeamTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterTeamId");

                    b.ToTable("MasterTeam");
                });

            modelBuilder.Entity("Passion.Models.MasterUsefullLinks", b =>
                {
                    b.Property<int>("MasterUsefullLinksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterUsefullLinksId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterUsefullLinksName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterUsefullLinksUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterUsefullLinksId");

                    b.ToTable("MasterUsefullLinks");
                });

            modelBuilder.Entity("Passion.Models.MasterWhatPeopleSay", b =>
                {
                    b.Property<int>("MasterWhatPeopleSayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterWhatPeopleSayId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MasterWhatPeopleSayBreef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterWhatPeopleSayDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterWhatPeopleSayImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MasterWhatPeopleSayTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MasterWhatPeopleSayId");

                    b.ToTable("MasterWhatPeopleSay");
                });

            modelBuilder.Entity("Passion.Models.SystemSetting", b =>
                {
                    b.Property<int>("SystemSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemSettingId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("SystemSettingId");

                    b.ToTable("SystemSetting");
                });

            modelBuilder.Entity("Passion.Models.TransactionContactUs", b =>
                {
                    b.Property<int>("TransactionContactUsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionContactUsId"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("TransactionContactUsEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionContactUsMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionContactUsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionContactUsSubject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionContactUsId");

                    b.ToTable("TransactionContactUs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Passion.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Passion.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Passion.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Passion.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Passion.Models.MasterChooseItemMenu", b =>
                {
                    b.HasOne("Passion.Models.MasterChooseCategory", "MasterChooseCategory")
                        .WithMany()
                        .HasForeignKey("MasterChooseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterChooseCategory");
                });

            modelBuilder.Entity("Passion.Models.MasterPortfolioItemMenu", b =>
                {
                    b.HasOne("Passion.Models.MasterPortfolioCategoryMenu", "MasterPortfolioCategoryMenu")
                        .WithMany()
                        .HasForeignKey("MasterPortfolioCategoryMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterPortfolioCategoryMenu");
                });
#pragma warning restore 612, 618
        }
    }
}
